const List<Map<String, dynamic>> fetusGrowthTracking = [
  {
    "startWeek": 1,
    "endWeek": 4,
    "sizeLabel": "Poppy seed",
    "message": "A beautiful new journey begins as your little one starts to grow.",
  },
  {
    "startWeek": 4,
    "endWeek": 5,
    "sizeLabel": "Poppy seed",
    "message": "Tiny beginnings — your baby is just starting to grow.",
  },
  {
    "startWeek": 6,
    "endWeek": 7,
    "sizeLabel": "Blueberry",
    "message": "Your baby is growing quickly, with early features beginning to form.",
  },
  {
    "startWeek": 8,
    "endWeek": 9,
    "sizeLabel": "Cherry",
    "message": "Little arms, legs, and facial features are starting to take shape.",
  },
  {
    "startWeek": 10,
    "endWeek": 11,
    "sizeLabel": "Strawberry",
    "message": "Your baby is becoming more defined each week.",
  },
  {
    "startWeek": 12,
    "endWeek": 13,
    "sizeLabel": "Lime",
    "message": "Your baby is growing steadily and becoming more active.",
  },
  {
    "startWeek": 14,
    "endWeek": 15,
    "sizeLabel": "Peach",
    "message": "Your baby’s body is growing, and movements are becoming stronger.",
  },
  {
    "startWeek": 16,
    "endWeek": 17,
    "sizeLabel": "Avocado",
    "approxLengthCm": 11.5,
    "approxWeightGrams": 100,
    "message": "Your baby is now growing fast and may be moving more.",
  },
  {
    "startWeek": 18,
    "endWeek": 19,
    "sizeLabel": "Mango",
    "approxLengthCm": 15.0,
    "approxWeightGrams": 240,
    "message": "Tiny movements may soon become easier to feel.",
  },
  {
    "startWeek": 20,
    "endWeek": 21,
    "sizeLabel": "Banana",
    "approxLengthCm": 26.5,
    "approxWeightGrams": 360,
    "message": "You’re around the halfway mark, and your baby is becoming more active.",
  },
  {
    "startWeek": 22,
    "endWeek": 23,
    "sizeLabel": "Ear of corn",
    "approxLengthCm": 29.0,
    "approxWeightGrams": 500,
    "message": "Your baby is gaining weight and developing more defined features.",
  },
  {
    "startWeek": 24,
    "endWeek": 25,
    "sizeLabel": "Cantaloupe",
    "approxLengthCm": 34.5,
    "approxWeightGrams": 660,
    "message": "Your baby’s senses and movements continue to develop.",
  },
  {
    "startWeek": 26,
    "endWeek": 27,
    "sizeLabel": "Cauliflower",
    "approxLengthCm": 36.5,
    "approxWeightGrams": 875,
    "message": "Your baby is growing stronger and preparing for the final trimester.",
  },
  {
    "startWeek": 28,
    "endWeek": 29,
    "sizeLabel": "Eggplant",
    "approxLengthCm": 38.5,
    "approxWeightGrams": 1150,
    "message": "Welcome to the third trimester — your baby is gaining weight quickly.",
  },
  {
    "startWeek": 30,
    "endWeek": 31,
    "sizeLabel": "Coconut",
    "approxLengthCm": 41.0,
    "approxWeightGrams": 1500,
    "message": "Your baby is growing rounder and stronger each week.",
  },
  {
    "startWeek": 32,
    "endWeek": 33,
    "sizeLabel": "Pineapple",
    "approxLengthCm": 43.5,
    "approxWeightGrams": 1900,
    "message": "Your baby is practicing important skills for life after birth.",
  },
  {
    "startWeek": 34,
    "endWeek": 35,
    "sizeLabel": "Honeydew melon",
    "approxLengthCm": 46.0,
    "approxWeightGrams": 2380,
    "message": "Your baby is gaining weight and getting closer to meeting you.",
  },
  {
    "startWeek": 36,
    "endWeek": 37,
    "sizeLabel": "Romaine lettuce",
    "approxLengthCm": 48.5,
    "approxWeightGrams": 2900,
    "message": "Your baby is nearly ready, with organs continuing to mature.",
  },
  {
    "startWeek": 38,
    "endWeek": 40,
    "sizeLabel": "Watermelon",
    "approxLengthCm": 51.0,
    "approxWeightGrams": 3400,
    "message": "Your baby is ready to arrive and meet the world!",
  },
];

Map<String, dynamic>? getFetusGrowthByWeek(int week) {
  return fetusGrowthTracking.firstWhere(
    (item) => week >= item["startWeek"] && week <= item["endWeek"],
    orElse: () => {},
  );
}